#####
# merge term frequency for quadgram generated by fullcorp_tf_combiner.R
####


source('~/GitHub/jh_capstone/JHCap_lib.R')

outpath <- "training/070"
combi.tf4 <- numeric(0)

for (x in 1:5) {
  print(x)
  ptm <- proc.time()  # start timer
  load(file.path(outpath, paste0("tf4_full_", x, ".RData")))
  print(proc.time()-ptm)

  sorted.tf4 <- sort(full.tf4, decreasing=TRUE)
  # Eliminating all those that appear only once, to save space and resource
  # assumption is, even if in all 4 files it appears once, a count of 5 is negligible
  # eliminate appear only once reduce much more than 90% threshold
  
  cf4 <- length(sorted.tf4) - sum(sorted.tf4 == 1)
  cat(cf4)
  print(proc.time()-ptm)
  
  sorted.tf4 <- sorted.tf4[1:cf4]
  print(proc.time()-ptm)

  gc()
  print(proc.time()-ptm)
  
  #  full.tf1 <- c(full.tf1, tf1)
  #  full.tf1 <- tapply(full.tf1, names(full.tf1), sum)
  #  print(proc.time()-ptm)
  
  #  full.tf2 <- c(full.tf2, tf2)
  #  full.tf2 <- tapply(full.tf2, names(full.tf2), sum)
  #  print(proc.time()-ptm)
  
  combi.tf4 <- c(combi.tf4, sorted.tf4)
  print(proc.time()-ptm)
  
  combi.tf4 <- tapply(combi.tf4, names(combi.tf4), sum)
  print(proc.time()-ptm)

  save(combi.tf4, file=file.path(outpath, paste0("combi_tf4_", x, ".RData")))
  print(proc.time()-ptm)
  
  print("complete")
}

full.tf4 <- sort(combi.tf4, decreasing=TRUE)
save(full.tf4, file=file.path(outpath, "tf4_full.RData"))