#####
# merge term frequency for trigram generated by train_set_tf_combiner.R
####


source('~/GitHub/jh_capstone/JHCap_lib.R')

outpath <- "training/070"
combi.tf3 <- numeric(0)

for (x in 1:4) {
  print(x)
  ptm <- proc.time()  # start timer
  load(file.path(outpath, paste0("tf3_full_", x, ".RData")))
  print(proc.time()-ptm)

  sorted.tf3 <- sort(full.tf3, decreasing=TRUE)
  # Eliminating all those that appear only once, to save space and resource
  # assumption is, even if in all 4 files it appears once, a count of 4 is negligible
  # eliminate appear only once reduce much more than 90% threshold
  
  #cf3 <- calcFreqCutoff(sorted.tf3, .95)
  cf3 <- length(sorted.tf3) - sum(sorted.tf3 == 1)
  cat(cf3)
  print(proc.time()-ptm)
  
  sorted.tf3 <- sorted.tf3[1:cf3]
  print(proc.time()-ptm)

  gc()
  print(proc.time()-ptm)
  
  #  full.tf1 <- c(full.tf1, tf1)
  #  full.tf1 <- tapply(full.tf1, names(full.tf1), sum)
  #  print(proc.time()-ptm)
  
  #  full.tf2 <- c(full.tf2, tf2)
  #  full.tf2 <- tapply(full.tf2, names(full.tf2), sum)
  #  print(proc.time()-ptm)
  
  combi.tf3 <- c(combi.tf3, sorted.tf3)
  print(proc.time()-ptm)
  
  combi.tf3 <- tapply(combi.tf3, names(combi.tf3), sum)
  print(proc.time()-ptm)

  save(combi.tf3, file=file.path(outpath, paste0("combi_tf3_", x, ".RData")))
  print(proc.time()-ptm)
  
  print("complete")
}

full.tf3 <- sort(combi.tf3, decreasing=TRUE)
save(full.tf3, file=file.path(outpath, "tf3_full.RData"))